#!/usr/bin/env perl
use strict;
use warnings;
use lib '.';
use Text::CSV_PP;
use DB_File;
use open ':std', ':encoding(utf8)';
use List::Util qw/
    uniq
/;
use Encode qw/
    encode_utf8
    decode_utf8
/;
use Fcntl qw/
    SEEK_SET
/;

my $debug = 0;
if (@ARGV && $ARGV[0] eq '-d') {
    shift;
    $debug = 1;
}

if (@ARGV != 2) {
    die "usage: paramahavcheck directory ingestfile.csv\n";
}
my ($dir, $ingest) = @ARGV;
if (! -d $dir) {
    die "error: $dir is not a directory\n";
}
# we will assume that the directory is readable and executable
# and that the .txt files within are readable
if (! -r $ingest) {
    die "error: cannot open $ingest for reading\n";
}
if ($ingest !~ m{[.]csv \z}xms) {
    die "error: $ingest is not a .csv file\n";
}

=comment

id identifier dc.identifier?
aside from id and collection
the rest are dc. in alphabetical order
    except for
        dc.subject.other     coming after
        dc.subject.technique instead of coming after
        dc.subject.keyword

dc.subject     or
dc.subject.lcc or
dc.subject.lcsh  ?
    library of congress classification number (lcc)
    library of congress subject heading (lcsh)

the following headers will be enforced when examining the ingest.csv file
    - fatal errors are thrown if an unknown header is encountered
    - the ingest.csv file will be edited "in-place"
        and an ingest.csv.00 file will preserve the original
               ingest.csv.01 etc
    - the ingest.csv file will be edited thusly:
        + missing columns inserted with blank/null entries
            (unless ... dc.subject.technique)
        + columns reordered if needed
    - if examining the ingest.csv file in a spreadsheet
        becomes unwieldy because of the many empty columns
        they can be *hidden*.
    - empty columns will be deleted in a separate pass

any non .txt files in the directory cause a fatal error
the .txt files in the directory are examined
    and the basename (strip the .txt suffix) must appear in the
    ingest file as dc.title (sans suffix)
    otherwise fatal error

.txt files cannot have a comma in the name

if no fatal errors the processing of the .txt
    files will proceed

output from the ParaMahaVCheck perusing of the .txt files
should be mapped to these columns:
    dc.subject.keyword
        Column B of the MahaVcheck output file
        with all the "Official" Vocabulary words
        found in the document
    dc.subject.person
        Column C - person names in the document
    dc.subject.technique
        Column D - techniques in the document
    dc.subject.other
        Column E  (variations of keyword, person, techniques) 

add all headers in order
    but then remove a column entirely if there
    is no data at all in any of the rows.

'new' and 'discarded' words are added to master lists
    named new.csv and discarded.csv with three columns:
    header:
        word,nfiles,filenames
    word,nfiles,"file1.txt, file2.txt, ..."
        ordered alphabetically, unduplicated files
            so can run it twice with no further effect (idempotent)
    and save backups of original
    these two files will be edited MANUALLY as well
        adding words to vocabulary (from new.csv)
        adding words to excluded (from discard.csv)
        and removing them from new.csv or discarded.csv

=cut 

mkdir "backups" unless -d "backups";

# ? dc.contributor.other?
my @headers = qw/
    id
    collection
    dc.contributor
    dc.contributor.author
    dc.coverage
    dc.creator
    dc.date.accessioned
    dc.date.available
    dc.date.created
    dc.date.submitted
    dc.description
    dc.description.disclaimer
    dc.description.provenance
    dc.format.extent
    dc.format.medium
    dc.identifier.uri
    dc.identifier.externalURI
    dc.language.iso
    dc.relation
    dc.relation.ispartof
    dc.relation.ispartofseries
    dc.rights
    dc.rights.holder
    dc.rights.license
    dc.rights.uri
    dc.subject
    dc.subject.lcsh
    dc.subject.keyword
    dc.subject.person
    dc.subject.techniques
    dc.subject.other
    dc.title
    dc.title.alternate
/;
# these headers must have a non-blank answer
my @required = qw/
    id
    collection
    dc.coverage
    dc.creator
    dc.date.created
    dc.description
    dc.format.medium
    dc.language.iso
    dc.rights
    dc.rights.holder
    dc.rights.license
    dc.rights.uri
    dc.subject
    dc.title
    dc.title.alternate
/;
# dc.date.created must be dddd-dd-dd

my %valid_header = map { $_ => 1 } @headers;

open my $in, '<:encoding(utf8)', $ingest 
    or die "error: cannot open $ingest: $!";

my $err = 0;
my $csv = Text::CSV_PP->new({ binary => 1, auto_diag => 1});

my $first_header_aref = $csv->getline($in);
my %column_for;
my $i = 0;
for my $h (@$first_header_aref) {
    if (! exists $valid_header{$h}) {
        print "error: invalid header: $h\n";
        ++$err;
    }
    $column_for{$h} = $i;
    ++$i;
}
my %missing_header;
for my $h (@headers) {
    if (! exists $column_for{$h}) {
        $missing_header{$h} = 1;
    }
}
if (exists $missing_header{'dc.title'}) {
    print "error: no 'dc.title' header\n";
    ++$err;
}
if ($err) {
    exit;
}
if ($debug) {
    for my $er (sort keys %missing_header) {
        print "missing header: $er\n";
    }
}
#
# gather the files in the ingest file
# and do some checking of date format, required fields, etc
#
my %ingest_fnames;
while (my $aref = $csv->getline($in)) {
    # convert array ref to a hash with key of column header
    my %value_of;
    for my $h (@headers) {
        if (! exists $missing_header{$h}) {
            $value_of{$h} = $aref->[$column_for{$h}];
        }
    }
    my $f = $value_of{'dc.title'};
    $f =~ s{[.][a-z]+ \z}{}xms;     # trim any suffix
    if ($debug) {
        print "$f\n";
    }
    $ingest_fnames{$f} = 1;
    for my $r (@required) {
        if ($value_of{$r} !~ m{\S}xms) {
            print "error: missing required value: '$r' for $f\n";
            ++$err;
        }
    }
    my $dt = $value_of{'dc.date.created'};
    if ($dt && $dt !~ m{\A \d\d\d\d-\d\d-\d\d \z}xms) {
        # check for valid date?  nah.
        print "error: invalid 'dc.date.created': $dt for $f\n";
        ++$err;
    }
}
my @files = <$dir/*>;
FILE:
for my $f (@files) {
    if ($f !~ m{ [.]txt\z }xms) {
        print "error: $f is not a .txt file!\n";
        ++$err;
        next FILE;
    }
    if ($f =~ m{,}xms) {
        print "error: the name $f contains a comma!\n";
        ++$err;
        next FILE;
    }
    my $f2 = $f;
    $f2 =~ s{\A $dir/(.*)[.]txt \z}{$1}xms;
    if (! $ingest_fnames{$f2}) {
        print "error: no line for $f2 in $ingest!\n";
        ++$err;
    }
}
if ($err) {
    exit;
}
# okay.  no fatal errors.

# set everything up for processing the .txt files
# 6 DBM files
my (%vocab, %names, %techniques, %alternates, %lex, %excluded);
tie %vocab,      'DB_File', 'vocab.dbm';
tie %alternates, 'DB_File', 'alternates.dbm';
tie %names,      'DB_File', 'names.dbm';
tie %techniques, 'DB_File', 'techniques.dbm';
tie %lex,        'DB_File', 'lex.dbm';
tie %excluded,   'DB_File', 'excluded.dbm';

# 3 text files for space regexes
my @vocab_sp      = get_sp('vocab_sp.txt');
my @names_sp      = get_sp('names_sp.txt');
my @techniques_sp = get_sp('techniques_sp.txt');

# a file of Harvard-Kyoto and iTRANS words with 
# an initial capital letter.  make a lookup table.
my %caps;
open my $caps, '<', 'caps.txt'
    or die "no caps.txt: $!\n";
while (my $line = <$caps>) {
    chomp $line;
    $caps{$line} = 1;
}
close $caps;

sub get_sp {
    my ($fname) = @_;
    open my $in, '<', $fname or die "no $fname: $!\n";
    my @array = <$in>;
    close $in;
    chomp @array;
    return @array;
}

=comment

the new and discard word files
new.csv and discard.csv have this header line:
    "word",nfiles,filenames

we read them into hashes; for each
    the key is the word
    the value is comma separated list
        of .txt files containing the word

when we're done we write the hashes back
to the .csv files (while keeping a backup ...)
unduping and sorting the list of files

=cut

my (%new_words, %disc_words);
get_csv('new.csv',     \%new_words);
get_csv('discard.csv', \%disc_words);
sub get_csv {
    my ($fname, $href) = @_;
    open my $in, '<:encoding(utf8)', $fname
        or return;  # file doesn't exist yet
    my $head_aref = $csv->getline($in);     # header
    while (my $aref = $csv->getline($in)) {
        my $fcol = (@$aref == 2)? 1: 2;     # tmp??
        push @{$href->{$aref->[0]}}, split m{\s*,\s*}, $aref->[$fcol];
            # tricky!
    }
    close $in;
}
sub put_csv {
    my ($fname, $href) = @_;
    my $tmp_fname = "$fname.tmp";
    open my $out, '>:encoding(utf8)', $tmp_fname
        or die "cannot open $tmp_fname: $!\n";
    $csv->say($out, [qw/ word nfiles filenames /]);    # header
    for my $w (sort keys %$href) {
        my @files = uniq sort @{$href->{$w}};
        $csv->say($out, [ $w, scalar(@files), join(', ', @files) ]);
    }
    close $out;
    my $x = 0;
    while (-e "backups/$x.$fname") {
        ++$x;
    }
    rename $fname, "backups/$x.$fname";
    rename $tmp_fname, $fname;
}
sub add_word {
    my ($w, $fname, $href) = @_;
    push @{$href->{$w}}, $fname;
}

# variables to communicate from sub process to the loop below
# sort of a hack...
my ($dcs_keyword, $dcs_person, $dcs_technique, $dcs_other);

# decode_utf8, join, uniq, sort, split
sub fix {
    my ($sep, @words) = @_;
    my @arr;
    WORD:
    for my $w (@words) {
        if (! $w) {
            next WORD;
        }
        push @arr, split m{\Q$sep\E}xms, $w;
    }
    return decode_utf8(join $sep, uniq sort @arr);
}

sub process {
    my ($fname) = @_;
    open my $in, '<:encoding(utf8)', $fname
        or die "cannot open $fname: $!\n";
    my $no_dir_fname = $fname;
    $no_dir_fname =~ s{\A $dir/}{}xms;
    print "processing $no_dir_fname\n";

    my $full_text;
    {
        local $/;
        no warnings;
        $full_text = <$in>;
        #$full_text = encode_utf8($full_text);
        close $in;
    }
    # \pL is the unicode character class for 'letters'.
    # see perldoc perlunicode.
    # we look for words with at least 2 letters with
    # a possible ' or - in the middle.
    #
    my @words = $full_text =~ m!(\p{Letter}[\p{Letter}'’-]*\p{Letter})!xmsg; 
    if ($debug) {
        print "1: $fname: @words\n"; <STDIN>;
    }

    # what about single letter words like I or a??
    # ignored??
 
    # words that *begin* with a capital letter
    # should have that letter lowercased.
    # do not do this if a word is in the caps.txt file.
    #
    # this initial capital letter will mostly be A-Z but
    # maybe also the upper case diacritic'ed letters
    # like Ācāra => ācāra or śhabda => Śhabda
    #
    for my $w (@words) {
        $w =~ s{’s}{}xmsg;                  # Lakshmi’s
        $w =~ s{[\p{^Letter}…] \z}{}xmsg;   # terminal non-Letter - plus …
        if (! exists $caps{$w} && $w =~ m{\A \p{Lu}}xms) {
            $w =~ s{\A (\p{Lu}) }{lc $1}xmse;
        }
    }

    @words = uniq sort @words;

    if ($debug) {
        print "2: $fname: @words\n"; <STDIN>;
    }

    my @eng_san_words;
    my @name_words;
    my @technique_words;
    my @alt_words;
    WORD:
    for my $w (@words) {
        my $ew = encode_utf8($w);
        if (exists $names{$ew}) {
            my $x = $names{$ew};
            push @name_words, $x;
            if (exists $alternates{$x}) {
                push @alt_words, $alternates{$x};
            }
        }
        elsif (exists $techniques{$ew}) {
            my $x = $techniques{$ew};
            push @technique_words, $x;
            if (exists $alternates{$x}) {
                push @alt_words, $alternates{$x};
            }
            push @alt_words, $alternates{$x};
        }
        elsif (exists $vocab{$ew}) {
            my $x = $vocab{$ew};
            push @eng_san_words, $x;
            if (exists $alternates{$x}) {
                push @alt_words, $alternates{$x};
            }
        }
        else {
            # shall we include it in the new words list?
            # or toss it into the discard list
            if (exists $excluded{$ew}) {
                add_word($w, $no_dir_fname, \%disc_words);
            }
            elsif ($lex{$ew}) {
                add_word($w, $no_dir_fname, \%new_words);
            }
            elsif ($w =~ m{ly \z}xms) {
                my $x = $w;
                $x =~ s{ly \z}{}xms;
                if ($lex{$x}) {
                    add_word($w, $no_dir_fname, \%new_words);
                }
                else {
                    add_word($w, $no_dir_fname, \%disc_words);
                }
            }
            else {
                add_word($w, $no_dir_fname, \%disc_words);
            }
        }
    }
    # now for the 3 sets of regex space words
    for my $w (@vocab_sp) {
        my $sp = $w;
        $sp =~ s{\s+}{\\s+}xmsg;
        if ($full_text =~ m{$sp}xms) {
            my $ew = encode_utf8($w);
            my $x = $vocab{$ew};
            push @eng_san_words, $x;
            if (exists $alternates{$x}) {
                push @alt_words, $alternates{$x};
            }
        }
    }
    for my $w (@names_sp) {
        my $sp = $w;
        $sp =~ s{\s+}{\\s+}xmsg;
        if ($full_text =~ m{$sp}xms) {
            my $ew = encode_utf8($w);
            my $x = $names{$ew};
            push @name_words, $x;
            if (exists $alternates{$x}) {
                push @alt_words, $alternates{$x};
            }
        }
    }
    for my $w (@techniques_sp) {
        my $ew = encode_utf8($w);
        my $sp = $w;
        $sp =~ s{\s+}{\\s+}xmsg;
        if ($full_text =~ m{$sp}xms) {
            my $x = $techniques{$ew};
            push @technique_words, $x;
            if (exists $alternates{$x}) {
                push @alt_words, $alternates{$x};
            }
        }
    }
    $dcs_keyword   = fix('||', @eng_san_words);
    $dcs_person    = fix('||', @name_words);
    $dcs_technique = fix('||', @technique_words);
    $dcs_other     = fix('||', @alt_words);
}


# let's rewind the ingest.csv file and proceed
seek $in, 0, SEEK_SET;

# open the output file.
# we will rename it.
# and make a backup of the original ingest file.
#
my $ingest_outfile = $ingest . '_out';
open my $out, '>:encoding(utf8)', $ingest_outfile
    or die "error: cannot create $ingest_outfile: $!\n";
my %full_header;

$first_header_aref = $csv->getline($in);    # get header line

$csv->say($out, \@headers);          # print full complete header line
                                     # including any empty columns
# subsequent lines:
while (my $aref = $csv->getline($in)) {
    # again convert array ref to a hash with key of column header
    my %value_of;
    for my $h (@headers) {
        if (! exists $missing_header{$h}) {
            $value_of{$h} = $aref->[$column_for{$h}];
        }
    }

    my $f = "$dir/$value_of{'dc.title'}";
    $f =~ s{[.][a-z]+ \z}{}xms;     # trim suffix
    my $txt = "$f.txt";             # add .txt
    if (-e $txt) {
        process($txt);      # most of the work...
        $value_of{'dc.subject.keyword'}   = $dcs_keyword;
        $value_of{'dc.subject.person'}    = $dcs_person;
        $value_of{'dc.subject.technique'} = $dcs_technique;
        $value_of{'dc.subject.other'}     = $dcs_other;
    }
    else {
        print "skipping: NO $txt\n";
    }
    # the values in @header order:
    my @arr;
    my $j = 0;
    for my $h (@headers) {
        if ($missing_header{$h} && ! exists $value_of{$h}) {
            push @arr, '';
        }
        else {
            if ($value_of{$h} =~ m{\S}xms) {
                $full_header{$j} = 1;
            }
            push @arr, $value_of{$h};
        }
        ++$j;
    }
    $csv->say($out, \@arr);
}
close $in;
close $out;

# deal with %new_words and %discard_words
# write them back to .csv files keeping a backup...
put_csv('new.csv',  \%new_words);
put_csv('discard.csv', \%disc_words);

# rewrite the $ingest_outfile
# skipping all columns except those in keys %full_header
# by using an array slice.
my @full_cols = sort { $a <=> $b } keys %full_header;
open my $in2, '<:encoding(utf8)', $ingest_outfile
    or die "cannot open $ingest_outfile: $!\n";
my $ingest_outfile2 = $ingest_outfile . '2';
open my $out2, '>:encoding(utf8)', $ingest_outfile2
    or die "error: cannot create $ingest_outfile2: $!\n";
while (my $aref = $csv->getline($in2)) {
    $csv->say($out2, [ @$aref[ @full_cols ] ] );     # yes
}
close $in2;
close $out2;

# renamings
my $x = 0;
while (-e ("backups/$x.$ingest")) {
    ++$x;
}
rename $ingest, "backups/$x.$ingest";    # create the backup
unlink $ingest_outfile;             # remove intermediate file
rename $ingest_outfile2, $ingest;   # rename final to original
